@baseUrl = http://localhost:8080

### Signup
POST {{baseUrl}}/api/auth/signup
Content-Type: application/json

{
    "email": "myteste@mailinator.com",
    "password": "12345678",
    "fullName": "Teste Fulano"
}


### Login
# @name login
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
    "email": "myteste@mailinator.com",
    "password": "123456789"
}

@authToken = {{login.response.body.$.token}}


### Validate email
GET {{baseUrl}}/api/auth/validate-email
    ?email=myteste@mailinator.com


### Verify email
GET {{baseUrl}}/api/auth/verify-email
    ?token=uuid-token-gerado-123


### resend email verification
POST {{baseUrl}}/api/auth/resend-verification
Content-Type: application/json

{
    "email": "myteste@mailinator.com"
}


### Forgot password
POST {{baseUrl}}/api/auth/forgot-password
Content-Type: application/json

{
    "email": "myteste@mailinator.com"
}


### Reset password
POST {{baseUrl}}/api/auth/reset-password
Content-Type: application/json

{
    "token": "83bb2512-b295-43ac-9be0-2a28bd53efca",
    "newPassword": "12345678"
}


### Change password
POST {{baseUrl}}/api/auth/change-password
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "currentPassword": "12345678",
    "newPassword": "123456789"
}


### Current user
GET {{baseUrl}}/api/auth/current-user
Content-Type: application/json
Authorization: Bearer {{authToken}}


### Create user
POST {{baseUrl}}/api/users
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "email": "myteste2@mailinator.com",
    "password": "12345678",
    "fullName": "Teste 2",
    "role": "USER"
}


### Update user
PUT {{baseUrl}}/api/users/2
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "fullName": "Teste updt2",
    "role": "USER"
}

### Get all users
GET {{baseUrl}}/api/users
    ?page=0
    &size=10
    &search=Test
Content-Type: application/json
Authorization: Bearer {{authToken}}

### Delete user
DELETE {{baseUrl}}/api/users/2
Content-Type: application/json
Authorization: Bearer {{authToken}}
