@baseUrl = http://localhost:8080

### Signup
POST {{baseUrl}}/api/auth/signup
Content-Type: application/json

{
    "email": "myteste1@mailinator.com",
    "password": "12345678",
    "fullName": "Teste user2"
}


### Login
# @name login
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
    "email": "myteste@mailinator.com",
    "password": "123456789"
}

@authToken = {{login.response.body.$.token}}


### Validate email
GET {{baseUrl}}/api/auth/validate-email
    ?email=myteste@mailinator.com


### Verify email
GET {{baseUrl}}/api/auth/verify-email
    ?token=d6f5fecd-3ac8-4f5a-ba0c-381334e4e67c


### resend email verification
POST {{baseUrl}}/api/auth/resend-verification
Content-Type: application/json

{
    "email": "myteste@mailinator.com"
}

### Forgot password
POST {{baseUrl}}/api/auth/forgot-password
Content-Type: application/json

{
    "email": "myteste@mailinator.com"
}

### Reset password
POST {{baseUrl}}/api/auth/reset-password
Content-Type: application/json

{
    "token": "83bb2512-b295-43ac-9be0-2a28bd53efca",
    "newPassword": "12345678"
}


### Change password
POST {{baseUrl}}/api/auth/change-password
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "currentPassword": "12345678",
    "newPassword": "123456789"
}


### Current user
GET {{baseUrl}}/api/auth/current-user
Content-Type: application/json
Authorization: Bearer {{authToken}}


### Create user
POST {{baseUrl}}/api/users
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "email": "myteste2@mailinator.com",
    "password": "12345678",
    "fullName": "Teste 2",
    "role": "USER"
}


### Update user
PATCH {{baseUrl}}/api/users/3
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "fullName": "Teste user2",
    "role": "USER"
}

### Get all users
GET {{baseUrl}}/api/users
    ?page=0
    &size=10
    &search=Test
Content-Type: application/json
Authorization: Bearer {{authToken}}

### Delete user
DELETE {{baseUrl}}/api/users/2
Content-Type: application/json
Authorization: Bearer {{authToken}}

### Toggle user status
PATCH {{baseUrl}}/api/users/1/toggle-status
Content-Type: application/json
Authorization: Bearer {{authToken}}

### Change user role
PATCH {{baseUrl}}/api/users/1/change-role
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "role": "USER"
}

### Upload video
POST {{baseUrl}}/api/files/upload/video
Content-Type: multipart/form-data; boundary=boundary
Authorization: Bearer {{authToken}}

--boundary
Content-Disposition: form-data; name="file"; filename="videoTeste.mp4"
Content-Type: video/mp4

< C:\Users\Tchaves\Videos\WhatsAppVideo.mp4 
--boundary--

### Create video by admin
POST {{baseUrl}}/api/videos/admin
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "title": "Sample video title2",
    "description": "This is a sample video description",
    "src": "video-uuid-here",
    "poster": "poster-uuid-here",
    "year": 2026,
    "rating": "PG-22",
    "duration": 8100,
    "categories": ["Action", "Thriller"],
    "published": false
}

### Update video by admin
PUT {{baseUrl}}/api/videos/admin/2
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "title": "Sample video title 2",
    "description": "This is a sample video description",
    "src": "video-uuid-here2",
    "poster": "poster-uuid-here2",
    "year": 2026,
    "rating": "PG-23",
    "duration": 8100,
    "categories": ["Action", "Thriller"],
    "published": false
}

### Delete video by admin
DELETE {{baseUrl}}/api/videos/admin/2
Authorization: Bearer {{authToken}}

### Toggle video publish status by admin
PATCH {{baseUrl}}/api/videos/admin/1/publish
        ?value=true
Authorization: Bearer {{authToken}}

### Get all admin videos
GET {{baseUrl}}/api/videos/admin
    ?page=0
    &size=10
    &search=
Authorization: Bearer {{authToken}}

### Get video statistics through the admin
GET {{baseUrl}}/api/videos/admin/stats
Authorization: Bearer {{authToken}}

### Serve video
GET {{baseUrl}}/api/files/video/uuid-video
    ?range=0-100
Authorization: Bearer {{authToken}}

### Upload image
POST {{baseUrl}}/api/files/upload/image
Content-Type: multipart/form-data; boundary=boundary
Authorization: Bearer {{authToken}}

--boundary
Content-Disposition: form-data; name="file"; filename="Imagem1.png"
Content-Type: image/png

< C:\Users\Tchaves\Pictures\Imagem1.png
--boundary--

### Serve image
GET {{baseUrl}}/api/files/image/uuid-image
Authorization: Bearer {{authToken}}