@baseUrl = http://localhost:8080

### Signup
POST {{baseUrl}}/api/auth/signup
Content-Type: application/json

{
    "email": "myteste@mailinator.com",
    "password": "12345678",
    "fullName": "Teste Fulano"
}